delete from filechurn where churn=0;
delete from filechurn where added=0;
delete from filechurn where added=remvd;
delete from filechurn where extension not in ('bash','c','cmd','cpp','csh','idl','java','m4','ml','mli','mly','py','rb','sh','vb','vbs');
delete from filechurn where filename like 'setup.ml';
delete from filechurn where filename like '%.xml';
delete from filechurn where filename like '%.sql';
delete from filechurn where filename like '%.eps';
delete from filechurn where filename like '%.css';
delete from filechurn where filename like '%.jpg';
delete from filechurn where filename like '%.png';
delete from filechurn where filename like '%.gif';
delete from filechurn where filename like '%.tex';
delete from filechurn where filename like '%.svg';
delete from filechurn where filename like 'doc/%';
delete from filechurn where filename like 'docs/%';
delete from filechurn where filename like '%/doc/%';
delete from filechurn where filename like '%.doc';
delete from filechurn where filename like '%.docx';
