DROP TABLE IF EXISTS commit;
DROP TABLE IF EXISTS filechurn;
DROP TABLE IF EXISTS chunk;
DROP TABLE IF EXISTS filemap;
DROP TABLE IF EXISTS compmap;
DROP TABLE IF EXISTS travisci;
DROP TABLE IF EXISTS coveralls;
