UPDATE filemap SET type=0 where repo='xen';	
UPDATE filemap SET type=1 where repo='xen' and filename like 'xen/arch/x86/%';
UPDATE filemap SET type=1 where repo='xen' and filename like 'xen/common/%.c';
UPDATE filemap SET type=1 where repo='xen' and filename like 'xen/common/compat/%';
UPDATE filemap SET type=1 where repo='xen' and filename like 'xen/common/gcov/%';
UPDATE filemap SET type=1 where repo='xen' and filename like 'xen/common/hvm/%';
UPDATE filemap SET type=1 where repo='xen' and filename like 'xen/common/libelf/%';	
UPDATE filemap SET type=1 where repo='xen' and filename like 'xen/crypto/%';
UPDATE filemap SET type=1 where repo='xen' and filename like 'xen/drivers/%';
UPDATE filemap SET type=1 where repo='xen' and filename like 'xen/xsm/%';
UPDATE filemap SET type=0 where extension not in ('bash','c','cmd','cpp','csh','cs','idl','java','m4','ml','mli','mly','py','rb','sh','vb','vbs');
UPDATE filemap SET type=0 where filename like 'doc/%';
UPDATE filemap SET type=0 where filename like 'docs/%';
UPDATE filemap SET type=0 where filename like '%/doc/%';
UPDATE filemap SET type=0 where filename like '%/docs/%';
UPDATE filemap SET type=0  WHERE filename='setup.ml';
UPDATE filemap SET type=0  WHERE filename like '%/setup.ml';
UPDATE filemap SET type=0  WHERE filename='myocamlbuild.ml';
UPDATE filemap SET type=0  WHERE filename='Makefile';
UPDATE filemap SET type=0  WHERE filename like '%/Makefile';
UPDATE filemap SET type=0  WHERE filename like 'test/%';
UPDATE filemap SET type=0  WHERE filename like '%/test/%';
UPDATE filemap SET type=0  WHERE filename like 'test%/%';
UPDATE filemap SET type=0  WHERE filename like '%/test%/%';
UPDATE filemap SET type=0  WHERE filename like '%_test/%';
UPDATE filemap SET type=0  WHERE filename like '%/%_test/%';
delete from filechurn where churn=0;
delete from filechurn where added=0;
delete from filechurn where added=remvd;
UPDATE filechurn SET type=0 where repo='xen';
UPDATE filechurn SET type=1 where repo='xen' and filename like 'xen/arch/x86/%';
UPDATE filechurn SET type=1 where repo='xen' and filename like 'xen/common/%.c';
UPDATE filechurn SET type=1 where repo='xen' and filename like 'xen/common/compat/%';
UPDATE filechurn SET type=1 where repo='xen' and filename like 'xen/common/gcov/%';
UPDATE filechurn SET type=1 where repo='xen' and filename like 'xen/common/hvm/%';
UPDATE filechurn SET type=1 where repo='xen' and filename like 'xen/common/libelf/%';
UPDATE filechurn SET type=1 where repo='xen' and filename like 'xen/crypto/%';
UPDATE filechurn SET type=1 where repo='xen' and filename like 'xen/drivers/%';
UPDATE filechurn SET type=1 where repo='xen' and filename like 'xen/xsm/%';
UPDATE filechurn SET type=0 where extension not in ('bash','c','cmd','cpp','csh','cs','idl','java','m4','ml','mli','mly','py','rb','sh','vb','vbs');
UPDATE filechurn SET type=0 where filename like 'doc/%';
UPDATE filechurn SET type=0 where filename like 'docs/%';
UPDATE filechurn SET type=0 where filename like '%/doc/%';
UPDATE filechurn SET type=0 where filename like '%/docs/%';
UPDATE filechurn SET type=0  WHERE filename='setup.ml';
UPDATE filechurn SET type=0  WHERE filename like '%/setup.ml';
UPDATE filechurn SET type=0  WHERE filename='myocamlbuild.ml';
UPDATE filechurn SET type=0  WHERE filename='Makefile';
UPDATE filechurn SET type=0  WHERE filename like '%/Makefile';
UPDATE filechurn SET type=0  WHERE filename like 'test/%';
UPDATE filechurn SET type=0  WHERE filename like '%/test/%';
UPDATE filechurn SET type=0  WHERE filename like 'test%/%';
UPDATE filechurn SET type=0  WHERE filename like '%/test%/%';
UPDATE filechurn SET type=0  WHERE filename like '%_test/%';
UPDATE filechurn SET type=0  WHERE filename like '%/%_test/%';
